# Generated by Django 3.2.5 on 2021-07-16 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_uji', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengujian',
            fields=[
                ('rules', models.TextField()),
                ('cf_combine', models.FloatField()),
                ('data_uji', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data_uji.datauji')),
            ],
        ),
    ]
