# Generated by Django 3.2.5 on 2021-07-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengujian', '0002_rename_pengujian_datapengujian'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapengujian',
            name='kelas',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
