# Generated by Django 3.2.5 on 2021-07-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataUji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pasien', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.FloatField(default=0)),
                ('trestbps', models.FloatField(default=0)),
                ('chol', models.FloatField(default=0)),
                ('thalach', models.FloatField(default=0)),
                ('oldpeak', models.FloatField(default=0)),
                ('sex', models.FloatField(default=0)),
                ('cp', models.FloatField(default=0)),
                ('fbs', models.FloatField(default=0)),
                ('restach', models.FloatField(default=0)),
                ('exang', models.FloatField(default=0)),
                ('slope', models.FloatField(default=0)),
                ('ca', models.FloatField(default=0)),
                ('thal', models.FloatField(default=0)),
                ('target', models.IntegerField(default=0)),
            ],
        ),
    ]
